In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv(r"C:\Users\abhay\Downloads\archive\phishing_site_urls.csv")

In [6]:
data.head()

URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [7]:
data.tail()

URL Label
549341     23.227.196.215/   bad
549342  apple-checker.org/   bad
549343   apple-iclods.org/   bad
549344  apple-uptoday.org/   bad
549345   apple-search.info   bad

In [8]:
data.sample(10)

URL Label
129000  bobbchrysler.com/wp-admin/includes/www.tescoba...   bad
389569                             minnesota.edu/?id=1187  good
1316                         brandl.com.br/images/portal/   bad
10029                  abiraj.com.np/Paypal_Virefication/   bad
4034                              mondziks.w.interia.pl/?   bad
477589                    youtube.com/watch?v=piXCnsTCuhk  good
512278                     uwiyklntlxpxj.work/checkupdate   bad
494084  copy.com/kSdM8qlaldznAdaz/DHL_RECEIPT_TRACKING...   bad
314303                     dictionary30.com/meaning/Mirna  good
530835                           thetestserver.net/kemymr   bad

In [9]:
data.shape

(549346, 2)

In [10]:
data.size

1098692

In [11]:
data.describe()

URL   Label
count                       549346  549346
unique                      507195       2
top     jhomitevd2abj3fk.onion.to/    good
freq                            52  392924

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   URL     549346 non-null  object
 1   Label   549346 non-null  object
dtypes: object(2)
memory usage: 8.4+ MB


In [13]:
data.URL

0         nobell.it/70ffb52d079109dca5664cce6f317373782/...
1         www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...
2         serviciosbys.com/paypal.cgi.bin.get-into.herf....
3         mail.printakid.com/www.online.americanexpress....
4         thewhiskeydregs.com/wp-content/themes/widescre...
                                ...                        
549341                                      23.227.196.215/
549342                                   apple-checker.org/
549343                                    apple-iclods.org/
549344                                   apple-uptoday.org/
549345                                    apple-search.info
Name: URL, Length: 549346, dtype: object

In [14]:
data.Label

0         bad
1         bad
2         bad
3         bad
4         bad
         ... 
549341    bad
549342    bad
549343    bad
549344    bad
549345    bad
Name: Label, Length: 549346, dtype: object

In [15]:
data.isnull().sum()

URL      0
Label    0
dtype: int64

In [16]:
data.Label.value_counts()

Label
good    392924
bad     156422
Name: count, dtype: int64

In [17]:
good = data[data.Label == "good"]
bad = data[data.Label == "bad"]

In [18]:
good.shape

(392924, 2)

In [19]:
good.head()

URL Label
18231  esxcc.com/js/index.htm?us.battle.net/noghn/en/...  good
18232  wwweira¯&nvinip¿ncH¯wVö%ÆåyDaHðû/ÏyEùuË\nÓ6...  good
18233  'www.institutocgr.coo/web/media/syqvem/dk-óij...  good
18234                  Yìê‡
koãջΧDéÎl½ñ¡ââqtò¸/à; Í  good
18236  ruta89fm.com/images/AS@Vies/1i75cf7b16vc<Fd16...  good

In [20]:
good.sample(10)

URL Label
157891  chicago.blockshopper.com/cities/buffalo_grove/...  good
258777  wiki.answers.com/Q/What_is_chihuahua_relations...  good
337791                           filmsite.org/twelve.html  good
300589  cbssports.com/collegefootball/players/playerpa...  good
424483          rootsweb.ancestry.com/~ausvsac/Ballan.htm  good
57349   www.nps.gov/history/nr/twhp/wwwlps/lessons/21b...  good
202861  jenningssrhigh.mo.jsh.schoolinsites.com/?PageN...  good
240212                 smurfs.wikia.com/wiki/Farmer_Smurf  good
415813                  pornchixmovies.com/candy-samples/  good
386208  mcgi.state.mi.us/mgdl/framework/metadata/Osceo...  good

In [21]:
bad.shape

(156422, 2)

In [22]:
bad.head()

URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [23]:
bad.sample(10)

URL Label
106201                              xnfwq.com/index_f.asp   bad
544763                          thecodega.com/878hf33f34f   bad
116476  living4u.80port.net/zb/doc/file.index.htm/rema...   bad
120511      escueladeparapente.cl/doc/docu/pvalidate.html   bad
487300              www.comeinbaby.com/mac/getversion.php   bad
7287                    www.ttok.asia/login/en/login.html   bad
496252                                   www.tabsync.net/   bad
133493  grenadineshomes.com/includes/.https/?https://w...   bad
114389  lafayettebeauty.net/wp-content/plugins/2c8adb8...   bad
104297              pragueproject.org/datafile/weldone/nD   bad

In [24]:
good = good.sample(n=156422)
good.shape

(156422, 2)

In [25]:
bad.shape

(156422, 2)

In [26]:
data = pd.concat([good, bad], axis=0)

In [27]:
data.head()

URL Label
468543  yellowpages.ca/bus/Quebec/Montreal/Altitude-Sp...  good
443230               theartistlabels.com/mouton/1988.html  good
156438  carmenoswalt.theworldrace.org/?filename=redefi...  good
247181         theproudpenguin.livejournal.com/49707.html  good
259795                                winusvilottery.com/  good

In [28]:
data.shape

(312844, 2)

In [29]:
data.Label.value_counts()

Label
good    156422
bad     156422
Name: count, dtype: int64

In [30]:
import time
import nltk
from nltk.corpus import stopwords
import re
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer 
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [31]:
tokenizer = RegexpTokenizer(r'[A-Za-z]+')

In [32]:
data.URL[0]

'nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

In [33]:
tokenizer.tokenize(data.URL[0]) 

['nobell',
 'it',
 'ffb',
 'd',
 'dca',
 'cce',
 'f',
 'login',
 'SkyPe',
 'com',
 'en',
 'cgi',
 'bin',
 'verification',
 'login',
 'ffb',
 'd',
 'dca',
 'cce',
 'f',
 'index',
 'php',
 'cmd',
 'profile',
 'ach',
 'outdated',
 'page',
 'tmpl',
 'p',
 'gen',
 'failed',
 'to',
 'load',
 'nav',
 'login',
 'access']

In [34]:
print('Getting words tokenized ...')
t0= time.perf_counter()
data['text_tokenized'] = data.URL.map(lambda t: tokenizer.tokenize(t)) # doing with all rows
t1 = time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting words tokenized ...
Time taken 1.9356850999974995 sec


In [35]:
data.sample(5)

URL Label  \
101089  philmoirphotography.com.au/wp-includes/js/jcro...   bad   
500790                               symbolcontacttype.ru   bad   
353458  hollywood.com/photo/Shira_Lazar_Shira_Lazar/52...  good   
143384  answers.yahoo.com/question/index?qid=201111011...  good   
213582  minnesota.sbnation.com/minnesota-twins/2011/9/...  good   

                                           text_tokenized  
101089  [philmoirphotography, com, au, wp, includes, j...  
500790                            [symbolcontacttype, ru]  
353458  [hollywood, com, photo, Shira, Lazar, Shira, L...  
143384  [answers, yahoo, com, question, index, qid, AA...  
213582  [minnesota, sbnation, com, minnesota, twins, m...

In [36]:
stemmer = SnowballStemmer("english")

In [37]:
print('Getting words stemmed ...')
t0= time.perf_counter()
data['text_stemmed'] = data['text_tokenized'].map(lambda l: [stemmer.stem(word) for word in l])
t1= time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting words stemmed ...
Time taken 13.037156099999265 sec


In [38]:
data.sample(5)

URL Label  \
90074                     www.apdl.co.uk/isv/games/sg.htm  good   
294875                          brainwashed.com/godspeed/  good   
70611   mitpress.mit.edu/e-journals/Computer-Music-Jou...  good   
37893                 mittl.hu/blog/wp-includes/login.htm   bad   
508910                            vapevoo.net/data/feeder   bad   

                                           text_tokenized  \
90074            [www, apdl, co, uk, isv, games, sg, htm]   
294875                       [brainwashed, com, godspeed]   
70611   [mitpress, mit, edu, e, journals, Computer, Mu...   
37893         [mittl, hu, blog, wp, includes, login, htm]   
508910                       [vapevoo, net, data, feeder]   

                                             text_stemmed  
90074             [www, apdl, co, uk, isv, game, sg, htm]  
294875                           [brainwash, com, godspe]  
70611   [mitpress, mit, edu, e, journal, comput, music...  
37893           [mittl, hu, blog, wp, includ, login, htm]  
508910                       [vapevoo, net, data, feeder]

In [39]:
print('Getting joiningwords ...')
t0= time.perf_counter()
data['text_sent'] = data['text_stemmed'].map(lambda l: ' '.join(l))
t1= time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting joiningwords ...
Time taken 0.17810559999998077 sec


In [40]:
data.sample(5)

URL Label  \
125247  surubiproducciones.com/wp/wp-includes/1/jpg/ar...   bad   
49835             thepluginsite.com/products/photogalaxy/  good   
20019   gkjx168.com/images?us.battle.net/login/en/?ref...   bad   
501924                                    easysecure.net/   bad   
519636                                         mxp224.com   bad   

                                           text_tokenized  \
125247  [surubiproducciones, com, wp, wp, includes, jp...   
49835         [thepluginsite, com, products, photogalaxy]   
20019   [gkjx, com, images, us, battle, net, login, en...   
501924                                  [easysecure, net]   
519636                                         [mxp, com]   

                                             text_stemmed  \
125247  [surubiproduccion, com, wp, wp, includ, jpg, a...   
49835           [thepluginsit, com, product, photogalaxi]   
20019   [gkjx, com, imag, us, battl, net, login, en, r...   
501924                                   [easysecur, net]   
519636                                         [mxp, com]   

                                                text_sent  
125247      surubiproduccion com wp wp includ jpg art new  
49835                thepluginsit com product photogalaxi  
20019   gkjx com imag us battl net login en ref uqpzem...  
501924                                      easysecur net  
519636                                            mxp com

In [41]:
data = data.drop(['URL', 'text_tokenized', 'text_stemmed'], axis = 1)
data.head()

Label                                          text_sent
468543  good  yellowpag ca bus quebec montreal altitud sport...
443230  good                     theartistlabel com mouton html
156438  good  carmenoswalt theworldrac org filenam redefin f...
247181  good                 theproudpenguin livejourn com html
259795  good                                 winusvilotteri com

In [42]:
X = data.text_sent.values

In [43]:
Y = data.Label.values

In [44]:
X.shape

(312844,)

In [45]:
Y.shape

(312844,)

In [46]:
vector = TfidfVectorizer()
vector.fit(X)
X = vector.transform(X)

In [47]:
X.shape

(312844, 245279)

In [48]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2207354 stored elements and shape (312844, 245279)>
  Coords	Values
  (0, 5132)	0.32668943816430873
  (0, 7357)	0.435101322038779
  (0, 28552)	0.339199610433694
  (0, 29646)	0.18572578861489836
  (0, 95406)	0.11987494349103558
  (0, 138398)	0.24522610994170785
  (0, 164275)	0.4868834717818309
  (0, 172844)	0.27713664186003445
  (0, 195864)	0.24785012801488565
  (0, 237985)	0.323441864776495
  (1, 40737)	0.07656498768707432
  (1, 95406)	0.15924177283554464
  (1, 139234)	0.6959812714594664
  (1, 205299)	0.6959812714594664
  (2, 31744)	0.5069654190186648
  (2, 68723)	0.290749822096741
  (2, 72023)	0.45796140512878847
  (2, 155759)	0.13929025538016904
  (2, 176178)	0.4337466041408961
  (2, 207042)	0.4911049423847993
  (3, 40737)	0.08922779688012662
  (3, 95406)	0.1855781995221292
  (3, 123516)	0.5474822484561601
  (3, 206516)	0.8110871221708744
  (4, 40737)	0.11283768058673176
  :	:
  (312837, 212572)	0.1440776392611881
  (31283

In [49]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify = Y,random_state = 2)

In [50]:
print(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1763333 stored elements and shape (250275, 245279)>
  Coords	Values
  (0, 40737)	0.0746502806973803
  (0, 68205)	0.2852449871477484
  (0, 130214)	0.6785764465464661
  (0, 156019)	0.6129842614300259
  (0, 161052)	0.27721279611579985
  (1, 40737)	0.056619562363754795
  (1, 43333)	0.4010131097055421
  (1, 47836)	0.34983114739520677
  (1, 100188)	0.14701812800452163
  (1, 146676)	0.2828498331737458
  (1, 162383)	0.3789522470651778
  (1, 162553)	0.11826757136396117
  (1, 197217)	0.2913367329948148
  (1, 207742)	0.30030580661553585
  (1, 207782)	0.4403435056352992
  (1, 224411)	0.2922797030234043
  (2, 17210)	0.37918593656189564
  (2, 17447)	0.608185672547566
  (2, 63733)	0.22030616156231042
  (2, 108997)	0.5089674566204339
  (2, 155759)	0.19240961100680695
  (2, 229411)	0.2589610075987769
  (2, 229446)	0.2732458135748589
  (3, 6046)	0.1926421856749621
  (3, 40737)	0.04132837189903981
  :	:
  (250270, 34722)	0.2748065321089233
  (

In [51]:
Y_train

array(['good', 'good', 'good', ..., 'bad', 'good', 'good'], dtype=object)

In [52]:
print(Y_train)

['good' 'good' 'good' ... 'bad' 'good' 'good']


In [53]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 444021 stored elements and shape (62569, 245279)>

In [54]:
print(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 444021 stored elements and shape (62569, 245279)>
  Coords	Values
  (0, 95400)	0.19734929421769876
  (0, 145157)	0.1937734104087703
  (0, 194563)	0.6795237749668257
  (0, 218552)	0.6795237749668257
  (1, 3478)	0.3054381136407092
  (1, 8257)	0.0996463678750276
  (1, 18155)	0.1413263516462269
  (1, 18454)	0.3022809308423806
  (1, 32654)	0.1309091806251492
  (1, 34521)	0.3098829449900248
  (1, 34573)	0.1633867341742125
  (1, 39310)	0.11200499393719096
  (1, 40737)	0.06631665909828609
  (1, 49068)	0.11661343346159533
  (1, 50323)	0.21591371861931774
  (1, 50334)	0.25455201615898687
  (1, 53703)	0.2126249782263928
  (1, 68070)	0.4590495549143734
  (1, 70354)	0.29725691042341695
  (1, 71070)	0.14246163590632224
  (1, 124778)	0.08724156726078437
  (1, 142119)	0.2664320332191672
  (1, 159778)	0.10327806428628934
  (1, 162553)	0.06926148741787898
  (1, 182587)	0.13400704234647812
  :	:
  (62564, 187291)	0.2293345412187041
  (62565, 6

In [55]:
Y_test

array(['good', 'bad', 'good', ..., 'bad', 'good', 'good'], dtype=object)

In [56]:
print(Y_test)

['good' 'bad' 'good' ... 'bad' 'good' 'good']


In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [58]:
Y_train = le.fit_transform(Y_train)
Y_train

array([1, 1, 1, ..., 0, 1, 1])

In [59]:
Y_test = le.fit_transform(Y_test)
Y_test

array([1, 0, 1, ..., 0, 1, 1])

In [60]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [61]:
model.predict(X_test)

array([1, 0, 1, ..., 0, 1, 1])

In [62]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [63]:
training_data_accuracy

0.967623614024573

In [64]:
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [65]:
testing_data_accuracy

0.9496555802394157

In [66]:
data.text_sent[0]

'nobel it ffb d dca cce f login skype com en cgi bin verif login ffb d dca cce f index php cmd profil ach outdat page tmpl p gen fail to load nav login access'

In [67]:
testing = data.text_sent[0]
testing = [testing]
testing = vector.transform(testing)
model.predict(testing)

array([0])

In [68]:
import pickle
with open('model.pickle', 'wb') as file:
     pickle.dump(model, file)

In [69]:
with open('model.pickle', 'rb') as file:
     model = pickle.load(file)

In [70]:
testing = "www.google.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [71]:
testing = "www.xyzxcf"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [72]:
testing = "www.facebook.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [73]:
testing = "w.xyzxcf"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Fake Website


In [74]:
testing = "w.vgffh"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Fake Website


In [75]:
testing = "www.google.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website
